development:
  adapter: postgresql
  database: ovirtec2_development
  username: ovirtec2
  password: ovirtec2
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: ovirtec2_production
  username: ovirtec2
  password: ovirtec2
  host: localhost
  encoding: UTF8

