development:
  adapter: postgresql
  database: ovirtex_development
  username: ovirtex
  password: ovirtex
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: ovirtex_production
  username: ovirtex
  password: ovirtex
  host: localhost
  encoding: UTF8

